class Product {
  final String title;
  final String description;
  final String image;
  final String review;
  final int price;
  final String category;
  final double rate;
  int quantity;

  Product({
    required this.title,
    required this.description,
    required this.image,
    required this.review,
    required this.price,
    required this.category,
    required this.rate,
    required this.quantity,
  });
}

final List<Product> bestSellers = [
  Product(
      title: "Iced Coffee",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/iced_coffee.png",
      review: " (329 Reviews)",
      price: 119,
      category: "Iced Drinks",
      rate: 4.9,
      quantity: 1),
  Product(
      title: "Caramel Macchiato",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/caramel_macchiato.png",
      review: " (256 Reviews)",
      price: 149,
      category: "Iced Drinks",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Mango Cheesecake",
      description: "Lorem Ipsum",
      image: "images/milkshakes/mango_cheesecake.png",
      review: " (267 Reviews)",
      price: 149,
      category: "Milkshakes",
      rate: 4.7,
      quantity: 1),
  Product(
      title: "Green Apple",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/green_apple.png",
      review: " (286 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Blue Lychee",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/blue_lychee.png",
      review: " (261 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Cordon Bleu",
      description: "Lorem Ipsum",
      image: "images/big_plates/cordon_bleu.png",
      review: " (365 Reviews)",
      price: 219,
      category: "Big Plates",
      rate: 4.9,
      quantity: 1),
  Product(
      title: "Chicken Wings",
      description: "Lorem Ipsum",
      image: "images/big_plates/chicken_wings.png",
      review: " (304 Reviews)",
      price: 219,
      category: "Big Plates",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Nachos",
      description: "Lorem Ipsum",
      image: "images/snacks/nachos.png",
      review: " (442 Reviews)",
      price: 179,
      category: "Snacks",
      rate: 5.0,
      quantity: 1),
  Product(
      title: "Fries Overload",
      description: "Lorem Ipsum",
      image: "images/snacks/fries_overload.png",
      review: " (305 Reviews)",
      price: 199,
      category: "Snacks",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "He Brews Sandwich",
      description: "Lorem Ipsum",
      image: "images/sandwiches/he_brews_sandwich.png",
      review: " (503 Reviews)",
      price: 199,
      category: "Sandwiches",
      rate: 5.0,
      quantity: 1),
];

final List<Product> icedDrinks = [
  Product(
      title: "Iced Americano",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/iced_americano.png",
      review: " (101 Reviews)",
      price: 119,
      category: "Iced Drinks",
      rate: 4.6,
      quantity: 1),
  Product(
      title: "Iced Coffee",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/iced_coffee.png",
      review: " (329 Reviews)",
      price: 119,
      category: "Iced Drinks",
      rate: 4.9,
      quantity: 1),
  Product(
      title: "Iced Latte",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/iced_latte.png",
      review: " (153 Reviews)",
      price: 129,
      category: "Iced Drinks",
      rate: 4.5,
      quantity: 1),
  Product(
      title: "Iced Mocha",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/iced_mocha.png",
      review: " (312 Reviews)",
      price: 129,
      category: "Iced Drinks",
      rate: 4.9,
      quantity: 1),
  Product(
      title: "Caramel Macchiato",
      description: "Lorem Ipsum",
      image: "images/iced_drinks/caramel_macchiato.png",
      review: " (256 Reviews)",
      price: 149,
      category: "Iced Drinks",
      rate: 4.8,
      quantity: 1),
];

final List<Product> milkShakes = [
  Product(
      title: "Mango Graham",
      description: "Lorem Ipsum",
      image: "images/milkshakes/mango_graham.png",
      review: " (275 Reviews)",
      price: 149,
      category: "Milkshakes",
      rate: 4.5,
      quantity: 1),
  Product(
      title: "Choco Mint",
      description: "Lorem Ipsum",
      image: "images/milkshakes/choco_mint.png",
      review: " (261 Reviews)",
      price: 149,
      category: "Milkshakes",
      rate: 4.0,
      quantity: 1),
  Product(
      title: "Matcha",
      description: "Lorem Ipsum",
      image: "images/milkshakes/matcha.png",
      review: " (230 Reviews)",
      price: 179,
      category: "Milkshakes",
      rate: 4.3,
      quantity: 1),
  Product(
      title: "Strawberry Cheesecake",
      description: "Lorem Ipsum",
      image: "images/milkshakes/strawberry_cheesecake.png",
      review: " (165 Reviews)",
      price: 149,
      category: "Milkshakes",
      rate: 4.4,
      quantity: 1),
  Product(
      title: "Mango Cheesecake",
      description: "Lorem Ipsum",
      image: "images/milkshakes/mango_cheesecake.png",
      review: " (267 Reviews)",
      price: 149,
      category: "Milkshakes",
      rate: 4.7,
      quantity: 1),
  Product(
      title: "Blueberry Cheesecake",
      description: "Lorem Ipsum",
      image: "images/milkshakes/blueberry_cheesecake.png",
      review: " (257 Reviews)",
      price: 149,
      category: "Milkshakes",
      rate: 4.6,
      quantity: 1),
];

final List<Product> fruitSlush = [
  Product(
      title: "Lemon Cucumber",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/lemon_cucumber.png",
      review: " (126 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 4.5,
      quantity: 1),
  Product(
      title: "Honey Lemonade",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/honey_lemonade.png",
      review: " (187 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 4.3,
      quantity: 1),
  Product(
      title: "Passion Mango",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/passion_mango.png",
      review: " (99 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 3.9,
      quantity: 1),
  Product(
      title: "Green Apple",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/green_apple.png",
      review: " (286 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Blue Lychee",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/blue_lychee.png",
      review: " (261 Reviews)",
      price: 129,
      category: "Fruit Slush",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Blueberry Yogurt",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/blueberry_yogurt.png",
      review: " (217 Reviews)",
      price: 139,
      category: "Fruit Slush",
      rate: 4.6,
      quantity: 1),
  Product(
      title: "Strawberry Yogurt",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/strawberry_yogurt.png",
      review: " (189 Reviews)",
      price: 139,
      category: "Fruit Slush",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Mango Yogurt",
      description: "Lorem Ipsum",
      image: "images/fruit_slush/mango_yogurt.png",
      review: " (285 Reviews)",
      price: 139,
      category: "Fruit Slush",
      rate: 4.4,
      quantity: 1),
];

final List<Product> icedTea = [
  Product(
      title: "Lemon Lychee",
      description: "Lorem Ipsum",
      image: "images/iced_tea/lemon_lychee.png",
      review: " (351 Reviews)",
      price: 119,
      category: "Iced Tea",
      rate: 4.3,
      quantity: 1),
  Product(
      title: "Pasion Fruit",
      description: "Lorem Ipsum",
      image: "images/iced_tea/passion_fruit.png",
      review: " (253 Reviews)",
      price: 119,
      category: "Iced Tea",
      rate: 4.5,
      quantity: 1),
  Product(
      title: "Honey Mango",
      description: "Lorem Ipsum",
      image: "images/iced_tea/honey_mango.png",
      review: " (164 Reviews)",
      price: 119,
      category: "Iced Tea",
      rate: 4.2,
      quantity: 1),
];

final List<Product> bigPlates = [
  Product(
      title: "Cordon Bleu",
      description: "Lorem Ipsum",
      image: "images/big_plates/cordon_bleu.png",
      review: " (365 Reviews)",
      price: 219,
      category: "Big Plates",
      rate: 4.9,
      quantity: 1),
  Product(
      title: "Chicken Wings",
      description: "Lorem Ipsum",
      image: "images/big_plates/chicken_wings.png",
      review: " (304 Reviews)",
      price: 219,
      category: "Big Plates",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Beef Tapa",
      description: "Lorem Ipsum",
      image: "images/big_plates/beef_tapa.png",
      review: " (201 Reviews)",
      price: 159,
      category: "Big Plates",
      rate: 4.3,
      quantity: 1),
  Product(
      title: "Burger Steak",
      description: "Lorem Ipsum",
      image: "images/big_plates/burger_steak.png",
      review: " (261 Reviews)",
      price: 189,
      category: "Big Plates",
      rate: 4.6,
      quantity: 1),
  Product(
      title: "German Sausage",
      description: "Lorem Ipsum",
      image: "images/big_plates/german_sausage.png",
      review: " (164 Reviews)",
      price: 179,
      category: "Big Plates",
      rate: 4.5,
      quantity: 1),
  Product(
      title: "BBQ Liempo",
      description: "Lorem Ipsum",
      image: "images/big_plates/bbq_liempo.png",
      review: " (286 Reviews)",
      price: 179,
      category: "Big Plates",
      rate: 4.5,
      quantity: 1),
];

final List<Product> snacks = [
  Product(
      title: "Nachos",
      description: "Lorem Ipsum",
      image: "images/snacks/nachos.png",
      review: " (442 Reviews)",
      price: 179,
      category: "Snacks",
      rate: 5.0,
      quantity: 1),
  Product(
      title: "Fries Overload",
      description: "Lorem Ipsum",
      image: "images/snacks/fries_overload.png",
      review: " (305 Reviews)",
      price: 199,
      category: "Snacks",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Beef Quesadilla",
      description: "Lorem Ipsum",
      image: "images/snacks/beef_quesadilla.png",
      review: " (245 Reviews)",
      price: 179,
      category: "Snacks",
      rate: 4.7,
      quantity: 1),
  Product(
      title: "Potato Wedges",
      description: "Lorem Ipsum",
      image: "images/snacks/potato_wedges.png",
      review: " (210 Reviews)",
      price: 159,
      category: "Snacks",
      rate: 4.6,
      quantity: 1),
];

final List<Product> pasta = [
  Product(
      title: "Carbonara",
      description: "Lorem Ipsum",
      image: "images/pasta/carbonara.png",
      review: " (205 Reviews)",
      price: 199,
      category: "Pasta",
      rate: 4.7,
      quantity: 1),
  Product(
      title: "Baked Macaroni",
      description: "Lorem Ipsum",
      image: "images/pasta/baked_macaroni.png",
      review: " (201 Reviews)",
      price: 199,
      category: "Pasta",
      rate: 4.4,
      quantity: 1),
  Product(
      title: "Sausage Penne",
      description: "Lorem Ipsum",
      image: "images/pasta/sausage_penne.png",
      review: " (195 Reviews)",
      price: 189,
      category: "Pasta",
      rate: 4.4,
      quantity: 1),
  Product(
      title: "Tuna Pesto",
      description: "Lorem Ipsum",
      image: "images/pasta/tuna_pesto.png",
      review: " (239 Reviews)",
      price: 199,
      category: "Pasta",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Spanish Sardines",
      description: "Lorem Ipsum",
      image: "images/pasta/spanish_sardines.png",
      review: " (199 Reviews)",
      price: 179,
      category: "Pasta",
      rate: 4.5,
      quantity: 1),
];

final List<Product> sandwiches = [
  Product(
      title: "He Brews Sandwich",
      description: "Lorem Ipsum",
      image: "images/sandwiches/he_brews_sandwich.png",
      review: " (503 Reviews)",
      price: 199,
      category: "Sandwiches",
      rate: 5.0,
      quantity: 1),
  Product(
      title: "Egg and Tuna",
      description: "Lorem Ipsum",
      image: "images/sandwiches/egg_and_tuna.png",
      review: " (293 Reviews)",
      price: 179,
      category: "Sandwiches",
      rate: 4.8,
      quantity: 1),
  Product(
      title: "Tuna Applemelt",
      description: "Lorem Ipsum",
      image: "images/sandwiches/tuna_applemelt.png",
      review: " (254 Reviews)",
      price: 179,
      category: "Sandwiches",
      rate: 4.7,
      quantity: 1),
];
